#Spring Cloud Config SSL Connection
spring.cloud.config.tls.enabled=true
spring.cloud.config.tls.trust-store=configserver-truststore.p12
spring.cloud.config.tls.trust-store-password=changeit

#SSL
server.ssl.enabled=true
server.ssl.key-store=classpath:securitymanager-keystore.p12
server.ssl.key-store-password=SmPass2026
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=securitymanager